SABSR3-Group-2/drug_discovery_game

Get_r_groups.py
Script to generate pandas dataframe with r groups from raw data file
=> Initial script for generating r groups

combine.py
adding function to select molecule form dataset when given R group tags
=> Combiningstructures

game_scripts/Get_r_groups.py, game_scripts/r_groups_selection.py
Updated get_r_groups to remove H substructures from R1
Updated r_group_selection to be compatible with get_r_groups
=> Steph 411 rgroups

game_scripts/BasicGameLoop.py
updated basic game loop wot work as part of uptodate file structure in repository
=> basic workign ui with using placeholder functions

.github/workflows/unittest.yml, game_scripts/Get_r_groups.py, requirements.txt, tests/test_combine.py, tests/test_import.py
I have fixed the compatibility issues with unittest so the tests now pass. I created a virtual conda environment within the testing virtual machine that allowed RDkit to be installed, so the tests could be carried out. 
All tests are now passing
=> Holland cifixes

game_scripts/Get_r_groups.py
- Have fixed substructure removal so that R group A11 (a single hydrogen) is not completely removed
- Have modified script so the a dataframe can be created for any number of R groups
=> Steph 11 nov

game_scripts/r_groups_selection.py
added some documentation to r_groups_selection.py
=> added docstrings to r_groups_selection.py

game_scripts/BasicGameLoop.py
working version of basic command line interface
=> a working initial interface

game_scripts/BasicGameLoop.py
added ability to display graph of scores over the round
=> Tidying text ui

game_scripts/Get_r_groups.py, game_scripts/select_mols.py
Refactored r_groups_selection.py and Get_r_groups.py into select_mols.py. Need to write unit tests and update references from the old modules to the new one but the new module at least is fully Sphinx documented.
=> James 25nov

game_scripts/select_mols.py, tests/test_get_selec.csv, tests/test_select_mols.py
New test for `read_mols()` from select_mols.py
=> James 02dec

game_scripts/descriptors.py, game_scripts/select_mols.py, tests/test_descriptors.py
get_descriptors() and associated test
=> James 09dec

Documentation/Makefile, Documentation/conf.py, Documentation/index.rst, Documentation/make.bat
setup sphinx for documentation to integrate with read the docs
=> Sphinx setup

game_scripts/BasicGameLoop.py
- Added pricing to game loop script
- User provided with starting balance and can select assay to run, the cost of which is subtracted each round
- The game ends when the user cannot afford another assay
- Not charged if assay result is 'Not Made' or 'Not Assayed'
- Fixed typo in self.currentchoice
- Test will be added later
=> Steph 1512

game_scripts/filters.py, tests/test_filters.py
- Adapted PAINS filter scripts to incorporate ZINC, BRENK and NIH filters (hence file renaming)
- Can filter dataframe or check chosen molecule 
- Have updated test
=> Added multiple filter types in addition to PAINS

game_scripts/draganddrop.py, game_scripts/inventory.py, game_scripts/molecule_builder.py
MVP of molecule builder window (drag drop + inventory). Lot's of commented out code but works minimally.
=> James 3feb

game_scripts/molecule_builder.py
Added constant rebuilding functionality to molecule builder
=> James 24feb

game_scripts/feedback_buttons.py, game_scripts/molecule_builder.py
added hover help text and fixed bugs with filter buttons
=> James 14apr

game_scripts/analysis.py, game_scripts/feedback_buttons.py, game_scripts/molecule_builder.py
- Fixed some errors introduced when merging different versions of the analysis screen
- (self.mat_list was being used for two different purposes - have changed the card mats to self.card_mat_list)
- Fixed font in mol builder view
- Added some comments to the feedback screen
=> Steph 27 sep

game_scripts/feedback_buttons.py
- Prevent user from running more assays if they have run out of money/time, and prevent user from selecting assays that they do not have enough money/time to run
=> steph_28_sep

game_scripts/analysis.py, game_scripts/feedback_buttons.py, game_scripts/molecule_builder.py
- Added units to descriptor results in feedback screen
- Added comments to feedback screen
- Added comments to the cards portion of the analysis screen
=> Swills 28sep

game_scripts/descriptors.py
In response to issue #101 the inequality comparison has been changed from >= to >
=> Update descriptors.py correcting lipinski issue
